name: dynmap
main: org.dynmap.bukkit.DynmapPlugin
version: "${project.version}-${BUILD_NUMBER}"
authors: [FrozenCow, mikeprimm]
softdepend: [ Permissions, PermissionEx, bPermissions, PermissionsBukkit, SpoutMaterials ]
commands:
  dynmap:
    description: Controls Dynmap.
    usage: |
           /<command> hide - hides the player from the map.
           /<command> hide TheDude - hides the player 'TheDude' on the map.
           /<command> show - shows the player on the map.
           /<command> show TheDude - shows the player 'TheDude' on the map.
           /<command> render - Renders the tile at your location.
           /<command> fullrender - Render all maps for entire world from your location.
           /<command> fullrender world - Render all maps for entire world 'world'.
           /<command> fullrender world:mapname - Render map 'mapname' of world 'world'.
           /<command> radiusrender ## - Render at least ## block radius from your location on all maps.
           /<command> radiusrender ## mapname - Render at least ## block radius from your location on map 'mapname'
           /<command> radiusrender worldname x z ## - Render at least ## block radius from location x,z on world 'worldname'
           /<command> radiusrender worldname x z ## mapname - Render at least ## block radius from location x,z on world 'worldname' on map 'mapname'
           /<command> updaterender - Render updates starting at your location on all maps.
           /<command> updaterender mapname - Render updates starting at your location on give map
           /<command> updaterender worldname x z - Render updates starting at location x,z on world 'worldname' for all maps
           /<command> updaterender worldname x z mapname - Render updates starting at location x,z on world 'worldname' for given map
           /<command> cancelrender - Cancels any active renders on current world
           /<command> cancelrender world - Cancels any active renders of world 'world'
           /<command> stats - Show render statistics.
           /<command> stats world - Show render statistics for maps on world 'world'.
           /<command> triggerstats - Show render trigger statistics
           /<command> resetstats - Reset render statistics.
           /<command> resetstats world - Reset render statistics for maps on world 'world'.
           /<command> sendtoweb msg - Send message to web users
           /<command> purgequeue - Set tile update queue to empty
           /<command> pause - Show render pause state
           /<command> pause <all|none|full|update> - Set render pause state
           /<command> ids-for-ip <ipaddress> - Show player IDs that have logged in from given IP address
           /<command> ips-for-id <playerid> - Show IP addresses that have been used for the given player ID
           /<command> add-id-for-ip <playerid> <ipaddress> - Add player ID to given IP address
           /<command> del-id-for-ip <playerid> <ipaddress> - Delete player ID from given IP address
            
  dmarker:
    description: Manipulate map markers
    usage: |
           /<command> add <label> - add new marker with given label at current location (use double-quotes if spaces needed)
           /<command> add id:<id> <label> - add new marker with given ID at current location (use double-quotes if spaces needed)
           /<command> movehere <label> - move marker with given label to current location
           /<command> movehere id:<id> - move marker with given ID to current location
           /<command> update <label> icon:<icon> newlabel:<newlabel>- update marker with given ID with new label and/or icon
           /<command> delete <label> - delete marker with given label
           /<command> delete id:<id> - delete marker with given ID
           /<command> list - list details of all markers
           /<command> icons - list details of all icons
           /<command> addset <label> - add marker set with given label (ID=label)
           /<command> addset id:<id> <label> - add marker set with given ID and label
           /<command> updateset id:<id> newlabel:<label> - update marker set with given ID
           /<command> updateset <label> newlabel:<label> - update marker set with given label
           /<command> deleteset <label> - delete marker set with given label
           /<command> deleteset id:<id> - delete marker set with given ID
           /<command> listsets - list all marker sets
           /<command> addicon id:<id> <label> file:"filename" - install new icon
           /<command> updateicon id:<id> newlabel:<label> file:"filename" - update existing icon
           /<command> updateicon <label> newlabel:<label> file:"filename" - update existing icon
           /<command> deleteicon id:<id> - remove icon 
           /<command> deleteicon <label> - remove icon 
           /<command> addcorner - add corner to corner list using current location
           /<command> addcorner <x> <z> <world> - add corner with given x and z coordinate on given world to corner list
           /<command> clearcorners - clear corner list
           /<command> addarea <label> - add new area with given label using corner list
           /<command> addarea id:<id> <label> - add new area with given ID using corner list
           /<command> deletearea <label> - delete area with given label
           /<command> deletearea id:<id> <label> - delete area with given ID
           /<command> listareas - list details of all areas
           /<command> updatearea <label> <arg>:<value> ... - update attributes of area with given label
           /<command> updatearea id:<id> <arg>:<value> ... - update attributes of area with given ID
  dmap:
    description: List and modify dynmap configuration
    usage: |
           /<command> worldlist - list all worlds configured (enabled or disabled)
           /<command> worldset worldname enabled:<true|false> - enable or disable a world
           /<command> worldset worldname center:<x/y/z|here|default> - set map center for given world
           /<command> worldset worldname extrazoomout:<N> - set extra zoom out levels for given world
           /<command> maplist worldname - list all maps for given world
           /<command> mapdelete worldname:mapname - delete given map of given world
           /<command> mapadd worldname:mapname attrib:value attrib:value - create map on given world with given attributes
           /<command> mapset worldname:mapname attrib:value attrib:value - update given map on given world with given attributes
           /<command> worldreset worldname - reset given world to default template for world type
           /<command> worldreset worldname templatename - reset given world to given template
           
permissions:
  dynmap.*:
    description: Gives access to all dynmap functions
    children:
      dynmap.render: true
      dynmap.show.self: true
      dynmap.show.others: true
      dynmap.hide.self: true
      dynmap.hide.others: true
      dynmap.fullrender: true
      dynmap.radiusrender: true
      dynmap.updaterender: true
      dynmap.cancelrender: true
      dynmap.reload: true
      dynmap.stats: true
      dynmap.resetstats: true
      dynmap.sendtoweb: true
      dynmap.purgequeue: true
      dynmap.ids-for-ip: true
      dynmap.ips-for-id: true
      dynmap.pause: true
      dynmap.marker.add: true
      dynmap.marker.update: true
      dynmap.marker.movehere: true
      dynmap.marker.delete: true
      dynmap.marker.list: true
      dynmap.marker.icons: true
      dynmap.marker.sign: true
      dynmap.marker.addset: true
      dynmap.marker.updateset: true
      dynmap.marker.deleteset: true
      dynmap.marker.listsets: true
      dynmap.marker.addicon: true
      dynmap.marker.updateicon: true
      dynmap.marker.deleteicon: true
      dynmap.marker.addarea: true
      dynmap.marker.updatearea: true
      dynmap.marker.listareas: true
      dynmap.marker.deletearea: true
      dynmap.dmap.worldlist: true
      dynmap.dmap.worldset: true
      dynmap.dmap.worldreset: true
      dynmap.dmap.mapdelete: true
      dynmap.dmap.mapset: true
      dynmap.dmap.mapadd: true
      dynmap.dmap.perspectivelist: true
      dynmap.dmap.shaderlist: true
      dynmap.dmap.lightinglist: true
  dynmap.render:
    description: Allows /dynmap render command
    default: true
  dynmap.show.self:
    description: Allows /dynmap show (on self)
    default: true
  dynmap.show.others:
    description: Allows /dynmap show <player>
    default: op
  dynmap.hide.self:
    description: Allows /dynmap hide (on self)
    default: true
  dynmap.hide.others:
    description: Allows /dynmap hide <player>
    default: op
  dynmap.fullrender:
    description: Allows /dynmap fullrender or /dynmap fullrender <world>
    default: op
  dynmap.radiusrender:
    description: Allows /dynmap radiusrender
    default: op
  dynmap.updaterender:
    description: Allows /dynmap updaterender
    default: op
  dynmap.cancelrender:
    description: Allows /dynmap cancelrender <world>
    default: op
  dynmap.reload:
    description: Allows /dynmap reload
    default: op
  dynmap.stats:
    description: Allows /dynmap stats, /dynmap stats <world>, or /dynmap triggerstats
    default: true
  dynmap.resetstats:
    description: Allows /dynmap resetstats or /dynmap resetstats <world>
    default: op
  dynmap.sendtoweb:
    description: Allows /dynmap sendtoweb
    default: op
  dynmap.purgequeue:
    description: Allows /dynmap purgequeue
    default: op
  dynmap.pause:
    description: Allows /dynmap pause
    default: op
  dynmap.ids-for-ip:
    description: Allows /dynmap ids-for-ip
    default: op
  dynmap.ips-for-id:
    description: Allows /dynmap ips-for-id
    default: op
  dynmap.marker.add:
    description: Allows /dmarker add
    default: op
  dynmap.marker.update:
    description: Allows /dmarker update
    default: op
  dynmap.marker.movehere:
    description: Allows /dmarker movehere
    default: op
  dynmap.marker.delete:
    description: Allows /dmarker delete
    default: op
  dynmap.marker.list:
    description: Allows /dmarker list
    default: true
  dynmap.marker.icons:
    description: Allows /dmarker icons
    default: true
  dynmap.marker.sign:
    description: Allows creation of markers using signs
    default: op
  dynmap.marker.addset:
    description: Allows /dmarker addset
    default: op
  dynmap.marker.updateset:
    description: Allows /dmarker updateset
    default: op
  dynmap.marker.deleteset:
    description: Allows /dmarker deleteset
    default: op
  dynmap.marker.listsets:
    description: Allows /dmarker listsets
    default: true
  dynmap.marker.addicon:
    description: Allows /dmarker addicon
    default: op
  dynmap.marker.updateicon:
    description: Allows /dmarker updateicon
    default: op
  dynmap.marker.deleteicon:
    description: Allows /dmarker deleteicon
    default: op
  dynmap.marker.addarea:
    description: Allows /dmarker addarea, /dmarker addcorner, /dmarker clearcorners
    default: op            
  dynmap.marker.updatearea:
    description: Allows /dmarker updatearea
    default: op            
  dynmap.marker.listareas:
    description: Allows /dmarker listareas
    default: op            
  dynmap.marker.deletearea:
    description: Allows /dmarker deletearea
    default: op
  dynmap.dmap.worldlist:
    description: Allows /dmap worldlist
    default: op
  dynmap.dmap.worldset:
    description: Allows /dmap worldset
    default: op
  dynmap.dmap.worldreset:
    description: Allows /dmap worldreset
    default: op
  dynmap.dmap.mapdelete:
    description: Allows /dmap mapdelete
    default: op
  dynmap.dmap.mapset:
    description: Allows /dmap mapset
    default: op
  dynmap.dmap.mapadd:
    description: Allows /dmap mapadd
    default: op
  dynmap.dmap.perspectivelist:
    description: Allows /dmap perspectivelist
    default: op
  dynmap.dmap.shaderlist:
    description: Allows /dmap shaderlist
    default: op
  dynmap.dmap.lightinglist:
    description: Allows /dmap lightinglist
    default: op
    
